# site name
prefixName: Tianci
siteName: の小窝
# favicon and site master avatar
favicon: https://cdn.lovetianci.cn/themes/images/favicon.ico
avatar: https://cdn.lovetianci.cn/themes/images/cute.gif
url: https://lovetianci.cn/
description: 一身清贫怎敢入繁华，两袖清风岂能误佳人
# cdn没填，图片路径需要填写完整
#cdn: https://fastly.jsdelivr.net/gh/2016838087/SakuraHexoFile@master/
pjax: 1
# 1开启
mathjax: 0

notice: 被这风吹散的人说Ta爱的不深，被这雨淋湿的人说Ta不会冷
lazyloadImg: https://cdn.lovetianci.cn/themes/cdn/svg/orange.progress-bar-stripe-loader.svg

# https://fontawesome.dashgame.com/
menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    .NET: {path: /categories/DotNET/, fa: fa-code }, 
    SQL: {path: /categories/SQL/, fa: fa-file-code-o },
    Vue: {path: /categories/Vue/, fa: fa-file-text-o }, 
    Hexo: {path: /categories/Hexo/, fa: fa-houzz }, 
    随笔: {path: /categories/Other/, fa: fa-book }
  } }
  标签: { path: javascript:;, fa: fa-tags faa-shake, submenus: { 
    娱乐: {path: /tags/娱乐/, fa: fa-gamepad }, 
    技术: {path: /tags/技术/, fa: fa-pencil-square-o }, 
    面试: {path: /tags/面试题/, fa: fa-television },
    相册: {path: /photo, fa: fa-photo}
  } }
  # 音乐: { path: http://lovetianci.cn/onlinemusic/, fa: fa-headphones faa-shake }
  留言板: { path: /comment/, fa: fa-comments faa-shake }
  # 赞赏: { path: /donate/, fa: fa-heart faa-pulse }fa-th-list faa-bounce
  # 生活: { path: /life/, fa: fa-android faa-vertical }fa-list-ul faa-vertical
  心情: { path: /mood/, fa: fa-commenting-o faa-shake }
  友链: { path: /links/, fa: fa-link faa-shake }
  关于: { path: /about/, fa: fa-meetup faa-shake } 
  # 倒计时: { path: /CountDown, fa: fa-leaf faa-wrench  } 
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse faa-shake }

donate:
  alipay: https://fastly.jsdelivr.net/gh/2016838087/TianciShokaBlog@master/images/alipay.jpg
  wechat: https://fastly.jsdelivr.net/gh/2016838087/TianciShokaBlog@master/images/wechatpay.png

# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
# https://cdn.lovetianci.cn/themes/sakurajs/
# 背景图和sakura-app.js是master分支
homeArticleShown: 10
# 背景图片
bg:
  - https://cdn.lovetianci.cn/themes/images/background/0.jpg
  - https://cdn.lovetianci.cn/themes/images/background/1.jpg
  - https://cdn.lovetianci.cn/themes/images/background/2.jpg
  - https://cdn.lovetianci.cn/themes/images/background/3.jpg
  - https://cdn.lovetianci.cn/themes/images/background/4.jpg
  - https://cdn.lovetianci.cn/themes/images/background/5.jpg
  - https://cdn.lovetianci.cn/themes/images/background/6.jpg
  - https://cdn.lovetianci.cn/themes/images/background/7.jpg
  - https://cdn.lovetianci.cn/themes/images/background/8.jpg
  - https://cdn.lovetianci.cn/themes/images/background/9.jpg
  - https://cdn.lovetianci.cn/themes/images/background/10.jpg
  - https://cdn.lovetianci.cn/themes/images/background/11.jpg
  - https://cdn.lovetianci.cn/themes/images/background/12.jpg
  - https://cdn.lovetianci.cn/themes/images/background/13.jpg
  - https://cdn.lovetianci.cn/themes/images/background/14.jpg
  - https://cdn.lovetianci.cn/themes/images/background/15.jpg
  - https://cdn.lovetianci.cn/themes/images/background/16.jpg
  - https://cdn.lovetianci.cn/themes/images/background/17.jpg
  - https://cdn.lovetianci.cn/themes/images/background/18.jpg
  - https://cdn.lovetianci.cn/themes/images/background/19.jpg
  - https://cdn.lovetianci.cn/themes/images/background/20.jpg
  - https://cdn.lovetianci.cn/themes/images/background/21.jpg
  - https://cdn.lovetianci.cn/themes/images/background/22.jpg
  - https://cdn.lovetianci.cn/themes/images/background/23.jpg
  - https://cdn.lovetianci.cn/themes/images/background/24.jpg
  - https://cdn.lovetianci.cn/themes/images/background/25.jpg
  - https://cdn.lovetianci.cn/themes/images/background/26.jpg
  - https://cdn.lovetianci.cn/themes/images/background/27.jpg
  - https://cdn.lovetianci.cn/themes/images/background/28.jpg
  - https://cdn.lovetianci.cn/themes/images/background/29.jpg
  - https://cdn.lovetianci.cn/themes/images/background/30.jpg
  - https://cdn.lovetianci.cn/themes/images/background/31.jpg
  - https://cdn.lovetianci.cn/themes/images/background/32.jpg
  - https://cdn.lovetianci.cn/themes/images/background/33.jpg
  - https://cdn.lovetianci.cn/themes/images/background/34.jpg
  - https://cdn.lovetianci.cn/themes/images/background/35.jpg
  - https://cdn.lovetianci.cn/themes/images/background/36.jpg
  - https://cdn.lovetianci.cn/themes/images/background/37.jpg
  - https://cdn.lovetianci.cn/themes/images/background/38.jpg
  - https://cdn.lovetianci.cn/themes/images/background/39.jpg
  - https://cdn.lovetianci.cn/themes/images/background/40.jpg
  - https://cdn.lovetianci.cn/themes/images/background/41.jpg
  - https://cdn.lovetianci.cn/themes/images/background/X-Blades1.jpg
  - https://cdn.lovetianci.cn/themes/images/background/X-Blades2.jpg
  - https://cdn.lovetianci.cn/themes/images/background/X-Blades3.jpg
  - https://cdn.lovetianci.cn/themes/images/background/X-Blades4.jpg
  - https://cdn.lovetianci.cn/themes/images/background/X-Blades5.jpg

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
# 图片路径master
startdash: 
  - {url: http://lovetianci.cn/onlinemusic/, title: 在线音乐播放器, desc: TianciOnlineMusic, img: https://cdn.lovetianci.cn/themes/images/other/rain.jpg}
  - {url: http://lovetianci.cn/showdoc/web/#/, title: 在线文档编辑器, desc: TianciShowdoc, img: https://cdn.lovetianci.cn/themes/images/other/book.jpg}
  - {url: http://lovetianci.cn/wallpaper/, title: 在线桌面壁纸, desc: TianciWallpaper, img: https://cdn.lovetianci.cn/themes/images/other/dream.jpg}


# your site build time or founded date
siteBuildingTime: 01/05/2020

#social  url, img PC端配置
social:
  # github: {url: https://github.com/2016838087, img: https://cdn.lovetianci.cn/themes/cdn/img/github.png}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=2016838087&site=qq&menu=yes&jumpflag=1, img: https://cdn.lovetianci.cn/themes/cdn/img/qq.png}
  wechat: {url: /#, qrcode: /images/wechat.jpg, img: https://cdn.lovetianci.cn/themes/cdn/img/wechat.png}

#social  url, img 移动端配置
msocial:
  # github: {url: https://github.com/2016838087, fa: fa-github, color: 333}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=2016838087&site=11&menu=yes,fa: fa-qq, color: 333}
  wechat: {url: /#, qrcode: /images/wechat.jpg, img: /cdn/img/wechat.png}


# 视频地址为https://fastly.jsdelivr.net/gh/2016838087/Artitalk-emoji@master/Video/Unbroken.mp4
movies:
  url: https://fastly.jsdelivr.net/gh/2016838087/Artitalk-emoji@master/Video/
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: The Pet Girl of Sakurasou.mp4,Unbroken.mp4

# 迅雷音乐播放器
# 中文文档：https://github.com/MoePlayer/hexo-tag-aplayer/blob/master/docs/README-zh_cn.md
aplayer: 
  id: 2742570554
  # 网易云歌单id：4991304209
  server: tencent
  # 网易云server：netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: list
  preload: auto
  volume: 0.7
  mutex: true
  hideLrc: false #隐藏歌词

# Valine
valine: true
v_appId: gcyRrrTODColvahbgrSvApl5-MdYXbMMI
v_appKey: 5W43w4sQ6cVbCqfCTRN0h6Ta

